import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
// 📌 HELPERS
import { appLoginAction } from '../helpers';

const Home: NextPage = ({ jwt, secret }: { jwt: number; secret: string }) => {
  // --------------------------------------------------------------------------------
  // 📌  MAIN APP EXIT COMPONENT
  // --------------------------------------------------------------------------------
  console.log('🐞 jwt ', jwt);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Content</div>
      <div>{secret}</div>
    </div>
  );
};

export const getServerSideProps = async (context: any) => {
  console.log('getServerSideProps', context);
  const secret = process.env.GRAPHQL_URI;
  let jwt: string = '';

  try {
    // 📌 app login action to retrieve jwt
    jwt = await appLoginAction({
      identifier: process.env.LOGIN_USERNAME,
      password: process.env.LOGIN_PASSWORD,
    });
  } catch (error) {
    console.log('🐞 ', error);
  }

  return {
    props: {
      jwt,
      secret,
    },
  };
};

export default Home;
